development:
 adapter: mysql2
 database: blog_dev
 username: infibeam
 password:
 host: localhost
 socket: /var/run/mysqld/mysqld.sock
 
test:
 adapter: mysql2
 database: blog_dev
 username: infibeam
 password:
 host: localhost
production:
 adapter: mysql2
 database: blog_dev	
 username: infibeam
 password:
 host: localhost
